In [5]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [2]:
import pandas as pd

In [40]:
data = pd.read_excel("Quantity/Country 2017-2018.xlsx", header=None)
df = pd.DataFrame(data)

In [41]:
# Set the first visible row as column names
df.columns = df.iloc[0]
df = df.iloc[2:].reset_index(drop=True)

In [30]:
# df.columns = df.iloc[1]
# df = df.iloc[2:].reset_index(drop=True)

In [ ]:
# df.drop(columns=["S.No."], inplace=True)

In [ ]:
# df.head()

1,Country,Dec-2017 (R),Dec-2018 (R),%Growth,Jan-Dec2017 (R),Jan-Dec2018 (R),%Growth
0,BANGLADESH PR,0,0,-,500,500,0
1,EGYPT A RP,0,0,-,5,0,-
2,ETHIOPIA,0,0,-,12,800,6567
3,GEORGIA,0,0,-,1,0,-
4,GERMANY,0,0,-,0,2,-

In [42]:
df = df.loc[:, df.columns.notna()]

df.columns = (
    df.columns
    .astype(str)
    .str.strip()
)

In [43]:
print(list(df.columns))

['TradeStat->Meidb->Export->Commoditywise-all-countries']

In [46]:
import pandas as pd

df = pd.read_excel(
    "Quantity/Country 2017-2018.xlsx",
    header=None
)
df.columns = df.iloc[2]

df = df.iloc[3:].reset_index(drop=True)
df = df.loc[:, df.columns.notna()]
df.columns = (
    df.columns
    .astype(str)
    .str.replace(r"\s+", " ", regex=True) 
    .str.strip()                           
)
print(list(df.columns))
df.head()

['S.No.', 'Country', 'Dec-2017 (R)', 'Dec-2018 (R)', '%Growth', 'Jan-Dec2017 (R)', 'Jan-Dec2018 (R)', '%Growth']

2,S.No.,Country,Dec-2017 (R),Dec-2018 (R),%Growth,Jan-Dec2017 (R),Jan-Dec2018 (R),%Growth
0,1,BANGLADESH PR,0,0,-,500,500,0
1,2,EGYPT A RP,0,0,-,5,0,-
2,3,ETHIOPIA,0,0,-,12,800,6567
3,4,GEORGIA,0,0,-,1,0,-
4,5,GERMANY,0,0,-,0,2,-

In [48]:
df = pd.read_excel(
    "Quantity/Country 2017-2018.xlsx",
    header=None
)
df.columns = df.iloc[2]

df = df.iloc[3:].reset_index(drop=True)
df = df.loc[:, df.columns.notna()]
df.columns = (
    df.columns
    .astype(str)
    .str.replace(r"\s+", " ", regex=True) 
    .str.strip()                           
)
df.head()

2,S.No.,Country,Dec-2017 (R),Dec-2018 (R),%Growth,Jan-Dec2017 (R),Jan-Dec2018 (R),%Growth
0,1,BANGLADESH PR,0,0,-,500,500,0
1,2,EGYPT A RP,0,0,-,5,0,-
2,3,ETHIOPIA,0,0,-,12,800,6567
3,4,GEORGIA,0,0,-,1,0,-
4,5,GERMANY,0,0,-,0,2,-

In [32]:
df.columns = df.iloc[1]
df = df.iloc[2:].reset_index(drop=True)

df = df.loc[:, ~df.columns.astype(str).str.contains("Unnamed")]

df.drop(columns=["S.No."], inplace=True, errors="ignore")

df = df.dropna(subset=["Country"])

numeric_cols = ["Jan-Dec2017 (R)", "Jan-Dec2018 (R)"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[(df["Jan-Dec2017 (R)"] > 0) | (df["Jan-Dec2018 (R)"] > 0)]

KeyError: 'Jan-Dec2017 (R)'

In [13]:
df = pd.read_excel("Data/Book.xlsx")
df.head()

,S.NO,Commidity,Month,Year,Units,Month_Quantity,Monthly_Growth,Yearly_Quantity,Yearly_Growth,Monthly_Cost,Monthly_Cost Growth,Year Cost,Year Growth
0,1,Lithium Hydoxide and Oxide,January,2017,Kgs,9060,0.0,99682,0,1.35,0,13.64,0
1,2,Lithium Hydoxide and Oxide,February,2017,Kgs,200,35.1,99682,0,0.07,0,13.64,0
2,3,Lithium Hydoxide and Oxide,March,2017,Kgs,500,0.0,99682,0,0.11,0,13.64,0
3,4,Lithium Hydoxide and Oxide,April,2017,Kgs,5000,0.0,99682,0,0.68,0,13.64,0
4,5,Lithium Hydoxide and Oxide,May,2017,Kgs,29789,0.0,99682,0,4.34,0,13.64,0

In [12]:
df = df.drop(df.columns[13:22], axis=1)
df.head()
df.to_excel("Data/Book.xlsx", index=False)

In [24]:
def load_detailed_data(file_path):
    df = pd.read_excel(file_path)
    df = df.drop(df.columns[13:22], axis=1)
    # Normalize column names
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    # Convert string "nan" → real NaN
    df = df.replace(["nan", "NaN", ""], pd.NA)

    return df

In [30]:
df = load_detailed_data("Data/Graphite/graphite_import.xlsx")
df.to_excel("Data/Graphite/graphite_import.xlsx", index=False)

In [31]:
df.head()

,s.no,commidity,month,year,units,month_quantity,monthly_growth,yearly_quantity,yearly_growth,monthly_cost,monthly_cost_growth,year_cost,year_growth
0,1,Graphite,January,2022,Kgs,5815263,0,52169628,6,24.68,0,318.08,35.66
1,2,Graphite,February,2022,Kgs,4395247,0,52169628,6,25.23,0,318.08,35.66
2,3,Graphite,March,2022,Kgs,4971972,0,52169628,6,30.55,0,318.08,35.66
3,4,Graphite,April,2022,Kgs,3077115,0,52169628,6,0.54,0,318.08,35.66
4,5,Graphite,May,2022,Kgs,3972412,0,52169628,6,24.26,0,318.08,35.66